#include "illegal_argument_exception.h"
#include "no_ram_exception.h"
#include "no_cpu_exception.h"
#include "invalid_register_exception.h"
#include "invalid_address_exception.h"
#include "division_by_zero_exception.h"
